-- Create the token_usage table
CREATE TABLE public.token_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    chat_id UUID REFERENCES public.chats(id),
    model_id TEXT NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    total_tokens INTEGER NOT NULL,
    workspace_id UUID REFERENCES public.workspaces(id)
);

-- Add indexes for common query patterns
CREATE INDEX idx_token_usage_user_id ON public.token_usage(user_id);
CREATE INDEX idx_token_usage_workspace_id ON public.token_usage(workspace_id);
CREATE INDEX idx_token_usage_created_at ON public.token_usage(created_at);

-- Enable Row Level Security (RLS)
ALTER TABLE public.token_usage ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
-- Policy: Allow users to read their own token usage
CREATE POLICY "Allow individual user read access"
ON public.token_usage
FOR SELECT
USING (auth.uid() = user_id);

-- Policy: Allow users to insert their own token usage
CREATE POLICY "Allow individual user insert access"
ON public.token_usage
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Note: Consider if update/delete policies are needed. For simple logging, they might not be.
